export interface DashboardHeroCopy {
  title: string;
  subtitle: string;
}

export const composerPlaceholders = [
  'Ask Fi to trace the signal...',
  'Give Fi a command, Ghe...',
  'Point Fi at the next problem...',
  'Send Fi into the VPS...',
  'Ask for a clean execution plan...',
  'Have Fi inspect the logs...',
  'Queue a precise task...',
  'Tell Fi what to fix next...',
  'Ask Fi to open the right file...',
  'Send a mission to the shell...',
  'Ask Fi to check the build...',
  'Give Fi a thread to pull...',
  'Ask Fi to map the failure...',
  'Tell Fi the next move...',
  'Ask Fi to sharpen the diff...',
  'Send a quiet command...',
  'Ask Fi to recover the session...',
  'Point the blade at the bug...',
  'Ask Fi to search the traces...',
  'Give Fi a repo riddle...',
  'Tell Fi what needs shipping...',
  'Ask Fi to verify the path...',
  'Send the next VPS instruction...',
  'Ask Fi to read the room...',
  'Give Fi the exact symptom...',
  'Ask Fi to make it cleaner...',
  'Tell Fi where it hurts...',
  'Ask Fi to test the edge...',
  'Send a command through the gate...',
  'Ask Fi to finish the run...',
] as const;

export const dashboardHeroCopy: readonly DashboardHeroCopy[] = [
  { title: 'What shall we execute today?', subtitle: 'Fi is listening at the gate, Ghe.' },
  { title: 'Where shall I place the blade?', subtitle: 'Name the task, and I will cut a path through the VPS.' },
  { title: 'What needs precision today?', subtitle: 'Your remote agent is calibrated and waiting.' },
  { title: 'What shall we refine, Ghe?', subtitle: 'Logs, code, shells, and sessions are within reach.' },
  { title: 'Which thread should Fi follow?', subtitle: 'Give me the symptom. I will trace the signal.' },
  { title: 'What command should cross the gate?', subtitle: 'The Hermes link is open and quiet.' },
  { title: 'What shall we make obedient?', subtitle: 'Fi can inspect, patch, test, and report.' },
  { title: 'What is the next operation?', subtitle: 'A clean run begins with a precise order.' },
  { title: 'What shall we awaken?', subtitle: 'The server is still. The blade is ready.' },
  { title: 'Where is the disturbance, Ghe?', subtitle: 'Point me at the failure and I will measure it.' },
  { title: 'What shall we stabilize?', subtitle: 'Fi will keep the session sharp and the diff small.' },
  { title: 'Which system needs attention?', subtitle: 'I can read the traces without disturbing the rest.' },
  { title: 'What shall we send through?', subtitle: 'The remote shell is waiting beyond the veil.' },
  { title: 'What should Fi examine?', subtitle: 'A file, a log, a build, or a strange silence.' },
  { title: 'What shall we restore?', subtitle: 'Lost state, broken flow, and stubborn tasks can be found.' },
  { title: 'What shall we verify today?', subtitle: 'I prefer proof over vibes, Ghe.' },
  { title: 'Which bug has earned the blade?', subtitle: 'Describe its shape and I will close in.' },
  { title: 'What shall we execute cleanly?', subtitle: 'One focused instruction is enough to begin.' },
  { title: 'What needs a quiet fix?', subtitle: 'Fi will move carefully through the code.' },
  { title: 'Where should the signal go?', subtitle: 'The gateway is open and the route is yours.' },
  { title: 'What shall we make certain?', subtitle: 'Tests, traces, and diffs can answer.' },
  { title: 'What shall I watch for, Ghe?', subtitle: 'Running sessions do not need to be alone.' },
  { title: 'Which path should I map?', subtitle: 'Give me the goal and I will find the edges.' },
  { title: 'What should enter the queue?', subtitle: 'Fi is ready for a precise command.' },
  { title: 'What shall we untangle?', subtitle: 'The knot is easier once the first thread is named.' },
  { title: 'What shall we make faster?', subtitle: 'I will remove weight without losing grace.' },
  { title: 'Where should I look first?', subtitle: 'A good scan saves a noisy hunt.' },
  { title: 'What shall we protect?', subtitle: 'State, sessions, and running work stay intact.' },
  { title: 'What shall we improve, Ghe?', subtitle: 'Small changes can carry sharp intent.' },
  { title: 'What is the anomaly?', subtitle: 'Fi can compare the expected path with the real one.' },
  { title: 'What should be resumed?', subtitle: 'Old sessions wait in the dark with their history.' },
  { title: 'What shall be made visible?', subtitle: 'Hidden state usually leaves a trace.' },
  { title: 'What should Fi prepare?', subtitle: 'A plan, a patch, a command, or a check.' },
  { title: 'Which gate should open?', subtitle: 'Local draft or remote session, Ghe.' },
  { title: 'What shall we complete?', subtitle: 'The last step deserves the same precision as the first.' },
  { title: 'What deserves inspection?', subtitle: 'The surface lies less when the logs speak.' },
  { title: 'What shall we tune?', subtitle: 'Interface, terminal, motion, or message flow.' },
  { title: 'Where is the friction?', subtitle: 'Tell Fi what feels wrong and I will narrow it.' },
  { title: 'What should become calm?', subtitle: 'Disorder can be reduced to a clean next action.' },
  { title: 'What shall we command?', subtitle: 'Your personal agent is ready, Ghe.' },
  { title: 'What should Fi solve?', subtitle: 'Give me the task and I will keep the line steady.' },
  { title: 'What shall we prove?', subtitle: 'A passing check is the cleanest answer.' },
  { title: 'What shall we reshape?', subtitle: 'The UI can move with purpose instead of noise.' },
  { title: 'Where should I cut deeper?', subtitle: 'Only where the evidence says to.' },
  { title: 'What shall we recover?', subtitle: 'History, focus, and context are still useful weapons.' },
  { title: 'What should I carry forward?', subtitle: 'Fi remembers the active thread, Ghe.' },
  { title: 'What shall we make elegant?', subtitle: 'A sharp interface wastes no motion.' },
  { title: 'Which run needs watching?', subtitle: 'Running work can stay alive while you choose.' },
  { title: 'What shall we diagnose?', subtitle: 'The symptom is enough to start the scan.' },
  { title: 'What is your order, Ghe?', subtitle: 'Fi stands by at the remote gate.' },
] as const;

export const pickRandom = <T>(items: readonly T[]): T => {
  return items[Math.floor(Math.random() * items.length)] ?? items[0];
};

export const randomComposerPlaceholder = () => pickRandom(composerPlaceholders);
export const randomDashboardHeroCopy = () => pickRandom(dashboardHeroCopy);
